### PR TITLE
feat: implement manga and some anime endpoints.

### PR DESCRIPTION
**Pull request by ananasmoe**
## Added things
- anime
  - [x] getAnimeNews
  - [x] getAnimeForum
  - [x] getAnimeMoreInfo
  - [x] getAnimeRecommendations
  - [x] getAnimePictures
  - [x] getAnimeReviews
  - [x] getAnimeRelations
  - [x] getAnimeExternal

- genres
  - [x] getAnimeGenres 
  - [x] getMangaGenres

- manga
  - [x] getMangaFullById
  - [x] getMangaById
  - [x] getMangaCharacters
  - [x] getMangaNews
  - [x] getMangaTopics
  - [x] getMangaPictures
  - [x] getMangaStatistics
  - [x] getMangaMoreInfo
  - [x] getMangaRecommendations
  - [x] getMangaUserUpdates
  - [x] getMangaReviews
  - [x] getMangaRelations
  - [x] getMangaExternal
  - [x] getMangaSearch

- random
  - [x] getRandomAnime
  - [x] getRandomManga
  - [x] getRandomCharacters

### CODE REVIEW

**Comment by THEGOLDENPRO** [comment]
if there's any data models that can be reused in the anime side of things feel free to make a separate object for it like what I did with `Title()` and `Name()` in the `/helpers` directory.

**Comment by ananasmoe** [comment]
I did

**Comment by THEGOLDENPRO** [comment]
the cookery is fucking crazy

**Comment by ananasmoe** [comment]
I removed some endpoints because I’m going to go crazy if I have to do more deserialization.

**Comment by THEGOLDENPRO** [comment]
rip

image

**Comment by THEGOLDENPRO** [comment]
are these tests running in the same environment or something, I've never hit a rate limit error with the unit tests on my machine

**Comment by THEGOLDENPRO** [comment]
I added `JikanIterableResource` so you no longer have to repeat `__next__` and `__iter__` implementations. You still need to define those functions though and call `super()` or else we'll get zero type annotation and I don't know of any other way to fix that currently other than implementing them.

https://github.com/THEGOLDENPRO/anmoku/blob/0699950331376168b25ae00231193e66ec0ff7ab/anmoku/resources/anime/characters.py#L52-L56

**Comment by ananasmoe** [comment]
> are these tests running in the same environment or something, I've never hit a rate limit error with the unit tests on my machine

probably

**Comment by ananasmoe** [comment]
Should I change everything to `JikanIterableResource` for all resources that use iteration or will you do it?

**Comment by THEGOLDENPRO** [comment]
> Should I change everything to `JikanIterableResource` for all resources that use iteration or will you do it?

feel free to do them, I don't have anything to commit rn

**Comment by THEGOLDENPRO** [comment]
Are you happy to merge this?

**Comment by THEGOLDENPRO** [comment]
oh yeah we need to link all of this to the docs

**Comment by ananasmoe** [comment]
We can merge this if you want

**Comment by THEGOLDENPRO** [comment]
Alright I'm merging this and setting the documentation stuff as a seperate github issue

**Pull request merged**
